### ISSUE TITLE
results!!!

### ISSUE THREAD

**Issue by KENPOKASMMA1982** [Jaya-sys/Dhuunn#1]
woowwwwwwwwwww what amazing projectttttttttttttttttttttt.many congratulationsssssssssssssssssssssssss ..but please could you make one button load more to increase unlimited results?I AM BEGGING YOU MY FRIEND!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by KENPOKASMMA1982** [comment]
please I am begging you Jaya tell me you will make it!!!

**Comment by Jaya-sys** [comment]
@KENPOKASMMA1982  Hi! I have my exams going on currently will give you the updates very soon

**Comment by KENPOKASMMA1982** [comment]
I WISH YOU ALL THE BEST...GOOD LUCK JAYA!THANKS A LOT...HUGS FROM GREECE!I HOPE YOU WILL MAKE IT VERY SOON!

**Comment by KENPOKASMMA1982** [comment]
JAYA HAVE A NICE MONTH!TELL ME PLEASE DO YOU THINK THE WEEKEND YOU CAN MAKE IT?HUGS FROM GREECE!!!

**Comment by Jaya-sys** [comment]
@KENPOKASMMA1982 Hi I'm sorry i cannot make changes up to this weekend cause I still have my exams going on..

**Comment by KENPOKASMMA1982** [comment]
aaaaa ok Jaya dont worry!maybe next week my friend?

**Comment by KENPOKASMMA1982** [comment]
Jaya my friend nothing yet?

**Comment by Jaya-sys** [comment]
@KENPOKASMMA1982  I have to wait for a month due to some reason but feel free to make changes

**Comment by KENPOKASMMA1982** [comment]
OK MY FRIEND!!!PLEASE LET ME KNOW!!!

**Comment by KENPOKASMMA1982** [comment]
Jaya my friend do you believe untill this weekend you will make your amazing web load unlimited results?

**Comment by KENPOKASMMA1982** [comment]
JAYA MY FRIEND???

**Comment by Jaya-sys** [comment]
@KENPOKASMMA1982  Hi ! Im really sorry, i have not been able to follow up the project recently and the request limit for shazam core API has reached to the end. so until I don't get the request I am not able to make any changes. But I'll let you know when I will commit the changes. Thanks
